project:
  type: website
  output-dir: docs

website:
  title: "solaeche"
  navbar:
    left:
      - href: index.qmd
        text: Home  
      - href: finalproject_2.qmd
      	text: Project
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



