project:
  type: website
  output-dir: docs

website:
  title: "solaeche"
  navbar:
    left:
      - href: final-final_project.qmd
        text: Project
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



