project:
  type: website
  output-dir: docs

website:
  title: "solaeche"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
	finalproject_2.qmd

	

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



